### ISSUE TITLE
Very interesting and inspiring work!

### ISSUE THREAD

**Issue by squareRoot3** [MaoXinn/LightEA#1]
When do you plan to release the code? Can't wait to use it.

**Comment by MaoXinn** [comment]
of course, i think the code will be released next week.

--------------原始邮件--------------
发件人："sQrt3 ***@***.***&gt;;
发送时间：2022年10月22日(星期六) 晚上7:03
收件人："MaoXinn/LightEA" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[MaoXinn/LightEA] Very interesting and inspiring work! (Issue #1)
-----------------------------------

 

 
When do you plan to release the code? Can't wait to use it.
