### ISSUE TITLE
Understanding the structure of `ent_ids_*` and `triples_*` files

### ISSUE THREAD

**Issue by calyptis** [MaoXinn/LightEA#2]
I would like to run LightEA on datasets other than the ones provided in the `EA_datasets/` folder of this repository.
To this end, I would like to understand the format of the input files.
These files have been provided as is and I could not obtain documentation from DBpedia or similar sources on how they are created or structured.

From what I understand, files `ent_ids_1` and `ent_ids_2` list all the names of entities contained in ontology 1 and 2, respectively, alongside their unique ID. IDs are not shared between ontologies. An example in the case of `DBP_FR_EN` is the entity `http://fr.dbpedia.org/resource/Android`, which is given an ID of 4.

Files `triples_1` and `triples_2` contain the connection between entities in ontology 1 and 2, respectively. The second ID in these triples is itself an entity and not a relationship. If we use `ent_ids_*` files to convert triples from IDs to names, we get for example this triple in the case of `DBP_FR_EN`: 

- (http://fr.dbpedia.org/resource/Université_de_Montpellier, http://fr.dbpedia.org/resource/Prism_(album_de_Katy_Perry), http://fr.dbpedia.org/resource/Béziers)
- Or as IDs: (24620, 153, 10255)

Another aspect of the `triples_*` files, is that `triples_2` uses relationship entities (2nd entity in triples) that are not available in the corresponding `ent_ids_2` file but rather listed in the `ent_ids_1` file.

**Questions**: 
Is it correct to use `ent_ids_*` to convert the IDs in triples to actual, readable connections between entities?
If so, then:

- Why do triples not use any relationship but rather another entity in the 2nd position?
- Why do the second entity contained in triples of the second ontology use IDs that are only listed in the first ontology (i.e. file `ent_ids_1` instead of `ent_ids_2`)?

A clarification on these points would help me in transforming my knowledge graphs into the format required by LightEA.

**Comment by MaoXinn** [comment]
Actually, the dataset I upload is only a simple version.
There should be another file containing the relations-ids list.
The ids of relations and entities are totally independent.
The second position (relation id) of IDs should be gathered from that file.
Because LightEA and many previous methods do not use the textual information of relations, so many follow studies and repos do not upload the relations-ids file.

The full version could be found in this repo https://github.com/nju-websoft/JAPE.

**Comment by calyptis** [comment]
Thanks a lot for your prompt reply and the clarification!
