### ISSUE TITLE
Interpreting results

### ISSUE THREAD

**Issue by calyptis** [MaoXinn/LightEA#3]
I would like to access the suggested alignment match for every entity of a selected ontology.

I have specified all the entities in ontology 1 and 2 in the files `ent_ids_1` and `ent_ids_2`, respectively.
Already annotated alignment pairs are specified in `ref_ent_ids` and `sup_ent_ids`, with the former being used for training and the latter for test. 

As a side note, the code combines the pairs of both files and splits them randomly (see `load_aligned_pair()`). Hence, only one single file is actually needed.

In the notebook, in cell 9, the proposed alignments seem to be stored in the `temp_pair` variable, which is based on the test pairs and then consecutively simply added to the training pairs.
Therefore, if my understanding is correct, the training pairs added in the iteration in cell 9 to the original list of training pairs are actually the suggested alignments.

So it seems to me that the notebook in its current form is simply finding the best match between entities contained in the test pairs.

**Question**: How can I access the suggested match for every entity of a selected ontology? In other words, say for every entity in `ent_ids_1`, I would like to access the closest match from `ent_ids_2`.

**Comment by MaoXinn** [comment]
You can just put the entities that you want to align in candidates_x and candidates_y.
These two sets store the candidate entities of source and target KGs.

If you want to get the suggested alignment results, the variable "ranks" in "utils.py/test()" contains the alignment results.

**Comment by calyptis** [comment]
Thanks for your clarification on this.

I ended up setting

```
candidates_x = set([
    int(i.split("\t")[0]) 
    for i in open("ent_ids_1").readlines()
])

candidates_y = set([
    int(i.split("\t")[0]) 
    for i in open("ent_ids_2").readlines()
])
```

and store all candidates_x with their corresponding highest ranking candidate_y in a list (not just those that pass `threshold`).

The only challenge I am now facing is that only few pairs have a high similarity, most are very close to 0 even after several epochs.
Only less than 100 pairs make it past the threshold of `0.5` after the first epoch and this number drops quickly over the course of the update procedure. I suppose it has to do with the degree of connectivity of nodes and how much actual overlap there exists between the two graphs I am attempting to align.

**Comment by MaoXinn** [comment]
Yes， It definitely depends on the connectivity of the Graphs.
LightEA is a pure-structural method, so there has to be some structural similarity.
You can lower the threshold, but it may not work.
