### ISSUE TITLE
questions on translated_ent_name

### ISSUE THREAD

**Issue by steamedfish99** [MaoXinn/LightEA#4]
Interesting work! Notice there are DBP15k and srprs translated in translated_ent_name. but translated name  of DBP-WD and DBP-YG seem missing, can you provide it?

**Comment by MaoXinn** [comment]
These two datasets are monolingual, we didn't use entity name features.



---Original---
From: ***@***.***&gt;
Date: Fri, Oct 13, 2023 16:06 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [MaoXinn/LightEA] questions on translated_ent_name (Issue #4)




 
Interesting work! Notice there are DBP15k and srprs translated in translated_ent_name. but translated name  of DBP-WD and DBP-YG seem missing, can you provide it?

**Comment by steamedfish99** [comment]
Thanks for reply! What's the pre-trained word embedding used in the experiment?

**Comment by steamedfish99** [comment]
> Thanks for reply! What's the pre-trained word embedding used in the experiment?

Oh, I see. Glove, it's mentioned in the code.

**Comment by nxchenbnu** [comment]
Where did you get the translated name data? Did you use google translation or directly use other people's link? Thanks!!
